name: 'Las Dos Cronicas De La Historia '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74483
title: 'La historia tiene dos lados y dos interpretaciones, la de los vencedores y la de los oprimidos '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#f60001'
    - '#c5c5c5'
    - '#4b4b4b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
