typography_spectrum: 0.74483
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#f60001'
    - '#c5c5c5'
    - '#4b4b4b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Moises
  email: teme678@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/711680c9-7b9a-4efa-a0b8-677453a788ae.jpg
name: 'La Crónica Real De La Historia '
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Mi Blog
    url: 'https://moisesmt.wordpress.com/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7232b842-d814-4736-b4eb-56be2fa3be66.jpg
title: >-
  La historia tiene dos lados y dos interpretaciones, la de los vencedores y la
  de los oprimidos 
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/f1f8aa1b-cf4a-4c20-93ac-384a7b3d3648.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/f1f8aa1b-cf4a-4c20-93ac-384a7b3d3648.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Conociendo las Historias
purpose: []
