typography_spectrum: 0.74483
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#f60001'
    - '#c5c5c5'
    - '#4b4b4b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Moises
  email: teme678@gmail.com
name: 'La Crónica Real De La Historia '
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Mi Blog
    url: 'https://moisesmt.wordpress.com/'
    type: external
favicon: null
title: >-
  La historia tiene dos lados y dos interpretaciones, la de los vencedores y la
  de los oprimidos 
content: []
description: ''
purpose: []
